# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Kingfisher', '~> 2.3.1'
pod 'Alamofire', '~> 3.3.1'
pod 'SwiftyJSON', '~> 2.3.2'
pod 'SDCycleScrollView','~> 1.64'
pod 'SDAutoLayout', '~> 1.52'
pod 'MJExtension', '~> 3.0.10'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJRefresh', '~> 3.1.7'
pod 'FMDB', '~> 2.6.2'